/*
 * @Author: wanglijuan
 * @Date: 2024-12-04 22:15:58
 * @LastEditors: wanglijuan
 * @LastEditTime: 2024-12-04 22:28:14
 */
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>{children}</div>
  )
}
